// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtmvuHxF7UkrXQr04xZdH89ncMXrvUnmc',
    appId: '1:197901175414:web:7b875b8770812260822d57',
    messagingSenderId: '197901175414',
    projectId: 'logifit-health-app',
    authDomain: 'logifit-health-app.firebaseapp.com',
    storageBucket: 'logifit-health-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5D5uuqiYIg8Ugc8HhD1tUaUGQoclR0rc',
    appId: '1:197901175414:android:1dc1b4602dfc1187822d57',
    messagingSenderId: '197901175414',
    projectId: 'logifit-health-app',
    storageBucket: 'logifit-health-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPPBWXHyFy7jI9x3r9I-86eNKtDxgfjyg',
    appId: '1:197901175414:ios:fd9a922a66e6a205822d57',
    messagingSenderId: '197901175414',
    projectId: 'logifit-health-app',
    storageBucket: 'logifit-health-app.firebasestorage.app',
    iosClientId: '197901175414-m1rbh13gcg9mii2h704eifkia41ncubj.apps.googleusercontent.com',
    iosBundleId: 'com.logifit.health.logifitHealth',
  );
}
